export const AppStrings = {
  LogoAltText: 'Company logo',
  SearchGists: 'Search gists...',
  Login: 'Login',
  PublicGists: 'Public Gists',
  OpenMenu: 'Open Menu',
  SignedInAs: 'Signed in as',
  Signout: 'Signout',
  YourGists: 'Your Gists',
  StarredGists: 'Starred Gists',
  YourGithubProfile: 'Your GitHub profile',
  Help: 'Help',
  Name: 'Name',
  NotebookName: 'Notebook Name',
  Keyword: 'Keyword',
  Updated: 'Updated',
  Page: 'Page',
  Of: 'of',
  UpdatedAt: 'Updated at',
  InvalidDate: 'invalid date',
  Created: 'Created',
  GistName: 'gist_name',
  JohnDoe: 'John Doe',
  View: 'View',
  ViewGithubProfile: 'View GitHub Profile',
  AllGists: 'All Gists',
  $99Plus: '99+',
  NoGistsAvailable: 'No Gists Available',
  Fork: 'Fork',
  Star: 'Star',
  CreateGist: 'Create Gist',
  GistDescription: 'Gist Description',
  AddFile: 'Add file',
  DescriptionEmpty: 'Gist description cannot be empty',
  InvalidFilename:
    'Filename cannot start with "gistfile" followed by a number (e.g., gistfile1).',
  FileIsRequired: 'At least one file is required',
  GistCreated: 'Gist created',
  CreateGistError: 'Something went wrong while creating gist',
  DuplicateFileError: 'A file with this name has already been added.',
} as const;
