export const AppStrings = {
  LogoAltText: 'Company logo',
  SearchGists: 'Search gists...',
  Login: 'Login',
  PublicGists: 'Public Gists',
  OpenMenu: 'Open Menu',
  SignedInAs: 'Signed in as',
  Signout: 'Signout',
  YourGists: 'Your Gists',
  StarredGists: 'Starred Gists',
  YourGithubProfile: 'Your GitHub profile',
  Help: 'Help',
  Name: 'Name',
  NotebookName: 'Notebook Name',
  Keyword: 'Keyword',
  Updated: 'Updated',
  Page: 'Page',
  Of: 'of',
  UpdatedAt: 'Updated at',
  InvalidDate: 'invalid date',
} as const;
